name: docker

on: push

jobs:
  container:
    runs-on: ubuntu-latest
    container: trustworthysystems/camkes
    steps:
      - name: Run in container
        run: |
          : "${GIT_USER:=Snail}"
          : "${GIT_EMAIL:=<>}"
          : "${BASE_DIR:=$HOME/CASE}"

          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git config --global color.ui true
         
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/config
          chmod 700 $HOME/.ssh/config
          echo -e "Host gitlab.adventium.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config

          apt-get update
          apt-get install  -f -y --no-install-recommends p7zip-full
          
          mkdir -p $HOME/CASE/camkes
          cd $HOME/CASE/camkes
          repo init -u https://github.com/seL4/camkes-manifest.git
          repo sync
          pwd
          ls -alig
          du -a
          
          mkdir -p $HOME/CASE/camkes-vm-examples
          cd $HOME/CASE/camkes-vm-examples
          repo init -u https://github.com/seL4/camkes-vm-examples-manifest.git
          repo sync
          
          cd $HOME
          git clone --recur  https://github.com/sireum/hamr-codegen.git
          
          # see https://github.com/sireum/hamr-codegen-test/blob/master/scala/org/sireum/hamr/codegen/test/util/TestMode.scala
          export HamrTestModes=phantom,compile,camkes,generated_unit_tests,smt2
          echo "HamrTestModes=${HamrTestModes}"
          
          export SMT2_TIMEOUT=180000
          echo "SMT2_TIMEOUT=${SMT2_TIMEOUT}"
          
          export ALSO_TRANSPILE_VIA_CALLBACKS=true
          echo "ALSO_TRANSPILE_VIA_CALLBACKS=${ALSO_TRANSPILE_VIA_CALLBACKS}"
          
          $HOME/hamr-codegen/bin/build.cmd test
