name: docker

on: push

jobs:
  container:
    runs-on: ubuntu-latest
    container: trustworthysystems/camkes-cakeml
    steps:
      - name: Run in container
        run: |
          : "${GIT_USER:=Snail}"
          : "${GIT_EMAIL:=<>}"
          : "${CASE_DIR:=$HOME/CASE}"

          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git config --global color.ui true
         
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/config
          chmod 700 $HOME/.ssh/config
          echo -e "Host gitlab.adventium.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config

          apt-get update
          apt-get install  -f -y --no-install-recommends p7zip-full

          export CAMKES_DIR=$CASE_DIR/camkes
          mkdir -p $CAMKES_DIR
          cd $CAMKES_DIR
          repo init -u https://github.com/seL4/camkes-manifest.git
          repo sync

          export CAMKES_VM_EXAMPLES_DIR=$CASE_DIR/camkes-vm-examples
          mkdir -p $CAMKES_VM_EXAMPLES_DIR
          cd $CAMKES_VM_EXAMPLES_DIR
          repo init -u https://github.com/seL4/camkes-vm-examples-manifest.git
          repo sync


          # $HOME dir in the container is not owned by root for some reason
          # which causes camkes builds to fail as the 'stack' Haskell too 
          # can't create '$HOME/.stack' directory.  Don't know why we can 
          # create directories here but 'stack' can't
          chown root:root $HOME
          ls -laF
          
          cd $HOME
          git clone --recur  https://github.com/sireum/hamr-codegen.git
          
          # see https://github.com/sireum/hamr-codegen-test/blob/master/scala/org/sireum/hamr/codegen/test/util/TestMode.scala
          export HamrTestModes=phantom,compile,camkes,generated_unit_tests,smt2
          echo "HamrTestModes=${HamrTestModes}"
          
          export SMT2_TIMEOUT=180000
          echo "SMT2_TIMEOUT=${SMT2_TIMEOUT}"
          
          export ALSO_TRANSPILE_VIA_CALLBACKS=true
          echo "ALSO_TRANSPILE_VIA_CALLBACKS=${ALSO_TRANSPILE_VIA_CALLBACKS}"
          
          HAMR_TEST_PACKAGE_NAMES=org.sireum.hamr.codegen.test.normal.CodegenTest_CASE $HOME/hamr-codegen/bin/build.cmd test
